### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by geckotang**
I recommend to use `.editorconfig` for development. Please refer http://editorconfig.org/ about it.

### CODE REVIEW

**Comment by watilde** [comment]
LGTM! Could you please make this PR to develop?

**Comment by geckotang** [comment]
@watilde Oh, I'm sorry. I'm retrying to make this PRs to develop.

**Comment by geckotang** [comment]
@watilde I just made PRs  #12 to develop. Please make sure.

**Comment by watilde** [comment]
Don't say sorry please! Thanks as always for your PRs :smiley_cat:

**Pull request closed without merging**
